<?php

declare(strict_types=1);
/**
 * CheckVatResponse
 *
 * PHP version 8.1
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vies on-the-Web Endpoint
 *
 * This is the contract for Vies on-the-Web endpoints. The checkVat service supports exact and approximate matching at the same time. In order to retrieve the requestIdentifier, the information about requesterMemberStateCode and requesterNumber have to be provided.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cone\Vies\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Cone\Vies\ObjectSerializer;

/**
 * CheckVatResponse Class Doc Comment
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CheckVatResponse implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'CheckVatResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'countryCode' => 'string',
        'vatNumber' => 'string',
        'requestDate' => '\DateTime',
        'valid' => 'bool',
        'requestIdentifier' => 'string',
        'name' => 'string',
        'address' => 'string',
        'traderName' => 'string',
        'traderStreet' => 'string',
        'traderPostalCode' => 'string',
        'traderCity' => 'string',
        'traderCompanyType' => 'string',
        'traderNameMatch' => '\Cone\Vies\Model\Match',
        'traderStreetMatch' => '\Cone\Vies\Model\Match',
        'traderPostalCodeMatch' => '\Cone\Vies\Model\Match',
        'traderCityMatch' => '\Cone\Vies\Model\Match',
        'traderCompanyTypeMatch' => '\Cone\Vies\Model\Match',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'countryCode' => null,
        'vatNumber' => null,
        'requestDate' => 'date-time',
        'valid' => null,
        'requestIdentifier' => null,
        'name' => null,
        'address' => null,
        'traderName' => null,
        'traderStreet' => null,
        'traderPostalCode' => null,
        'traderCity' => null,
        'traderCompanyType' => null,
        'traderNameMatch' => null,
        'traderStreetMatch' => null,
        'traderPostalCodeMatch' => null,
        'traderCityMatch' => null,
        'traderCompanyTypeMatch' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'countryCode' => false,
        'vatNumber' => false,
        'requestDate' => false,
        'valid' => false,
        'requestIdentifier' => false,
        'name' => false,
        'address' => false,
        'traderName' => false,
        'traderStreet' => false,
        'traderPostalCode' => false,
        'traderCity' => false,
        'traderCompanyType' => false,
        'traderNameMatch' => false,
        'traderStreetMatch' => false,
        'traderPostalCodeMatch' => false,
        'traderCityMatch' => false,
        'traderCompanyTypeMatch' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'countryCode' => 'countryCode',
        'vatNumber' => 'vatNumber',
        'requestDate' => 'requestDate',
        'valid' => 'valid',
        'requestIdentifier' => 'requestIdentifier',
        'name' => 'name',
        'address' => 'address',
        'traderName' => 'traderName',
        'traderStreet' => 'traderStreet',
        'traderPostalCode' => 'traderPostalCode',
        'traderCity' => 'traderCity',
        'traderCompanyType' => 'traderCompanyType',
        'traderNameMatch' => 'traderNameMatch',
        'traderStreetMatch' => 'traderStreetMatch',
        'traderPostalCodeMatch' => 'traderPostalCodeMatch',
        'traderCityMatch' => 'traderCityMatch',
        'traderCompanyTypeMatch' => 'traderCompanyTypeMatch',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'countryCode' => 'setCountryCode',
        'vatNumber' => 'setVatNumber',
        'requestDate' => 'setRequestDate',
        'valid' => 'setValid',
        'requestIdentifier' => 'setRequestIdentifier',
        'name' => 'setName',
        'address' => 'setAddress',
        'traderName' => 'setTraderName',
        'traderStreet' => 'setTraderStreet',
        'traderPostalCode' => 'setTraderPostalCode',
        'traderCity' => 'setTraderCity',
        'traderCompanyType' => 'setTraderCompanyType',
        'traderNameMatch' => 'setTraderNameMatch',
        'traderStreetMatch' => 'setTraderStreetMatch',
        'traderPostalCodeMatch' => 'setTraderPostalCodeMatch',
        'traderCityMatch' => 'setTraderCityMatch',
        'traderCompanyTypeMatch' => 'setTraderCompanyTypeMatch',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'countryCode' => 'getCountryCode',
        'vatNumber' => 'getVatNumber',
        'requestDate' => 'getRequestDate',
        'valid' => 'getValid',
        'requestIdentifier' => 'getRequestIdentifier',
        'name' => 'getName',
        'address' => 'getAddress',
        'traderName' => 'getTraderName',
        'traderStreet' => 'getTraderStreet',
        'traderPostalCode' => 'getTraderPostalCode',
        'traderCity' => 'getTraderCity',
        'traderCompanyType' => 'getTraderCompanyType',
        'traderNameMatch' => 'getTraderNameMatch',
        'traderStreetMatch' => 'getTraderStreetMatch',
        'traderPostalCodeMatch' => 'getTraderPostalCodeMatch',
        'traderCityMatch' => 'getTraderCityMatch',
        'traderCompanyTypeMatch' => 'getTraderCompanyTypeMatch',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('countryCode', $data ?? [], null);
        $this->setIfExists('vatNumber', $data ?? [], null);
        $this->setIfExists('requestDate', $data ?? [], null);
        $this->setIfExists('valid', $data ?? [], null);
        $this->setIfExists('requestIdentifier', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('traderName', $data ?? [], null);
        $this->setIfExists('traderStreet', $data ?? [], null);
        $this->setIfExists('traderPostalCode', $data ?? [], null);
        $this->setIfExists('traderCity', $data ?? [], null);
        $this->setIfExists('traderCompanyType', $data ?? [], null);
        $this->setIfExists('traderNameMatch', $data ?? [], null);
        $this->setIfExists('traderStreetMatch', $data ?? [], null);
        $this->setIfExists('traderPostalCodeMatch', $data ?? [], null);
        $this->setIfExists('traderCityMatch', $data ?? [], null);
        $this->setIfExists('traderCompanyTypeMatch', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets countryCode
     *
     * @return string|null
     */
    public function getCountryCode(): ?string
    {
        return $this->container['countryCode'];
    }

    /**
     * Sets countryCode
     *
     * @param string|null $countryCode countryCode
     *
     * @return $this
     */
    public function setCountryCode(?string $countryCode): static
    {
        if (is_null($countryCode)) {
            throw new InvalidArgumentException('non-nullable countryCode cannot be null');
        }
        $this->container['countryCode'] = $countryCode;

        return $this;
    }

    /**
     * Gets vatNumber
     *
     * @return string|null
     */
    public function getVatNumber(): ?string
    {
        return $this->container['vatNumber'];
    }

    /**
     * Sets vatNumber
     *
     * @param string|null $vatNumber vatNumber
     *
     * @return $this
     */
    public function setVatNumber(?string $vatNumber): static
    {
        if (is_null($vatNumber)) {
            throw new InvalidArgumentException('non-nullable vatNumber cannot be null');
        }
        $this->container['vatNumber'] = $vatNumber;

        return $this;
    }

    /**
     * Gets requestDate
     *
     * @return \DateTime|null
     */
    public function getRequestDate(): ?\DateTime
    {
        return $this->container['requestDate'];
    }

    /**
     * Sets requestDate
     *
     * @param \DateTime|null $requestDate requestDate
     *
     * @return $this
     */
    public function setRequestDate(?\DateTime $requestDate): static
    {
        if (is_null($requestDate)) {
            throw new InvalidArgumentException('non-nullable requestDate cannot be null');
        }
        $this->container['requestDate'] = $requestDate;

        return $this;
    }

    /**
     * Gets valid
     *
     * @return bool|null
     */
    public function getValid(): ?bool
    {
        return $this->container['valid'];
    }

    /**
     * Sets valid
     *
     * @param bool|null $valid valid
     *
     * @return $this
     */
    public function setValid(?bool $valid): static
    {
        if (is_null($valid)) {
            throw new InvalidArgumentException('non-nullable valid cannot be null');
        }
        $this->container['valid'] = $valid;

        return $this;
    }

    /**
     * Gets requestIdentifier
     *
     * @return string|null
     */
    public function getRequestIdentifier(): ?string
    {
        return $this->container['requestIdentifier'];
    }

    /**
     * Sets requestIdentifier
     *
     * @param string|null $requestIdentifier requestIdentifier
     *
     * @return $this
     */
    public function setRequestIdentifier(?string $requestIdentifier): static
    {
        if (is_null($requestIdentifier)) {
            throw new InvalidArgumentException('non-nullable requestIdentifier cannot be null');
        }
        $this->container['requestIdentifier'] = $requestIdentifier;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return $this
     */
    public function setName(?string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress(): ?string
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address address
     *
     * @return $this
     */
    public function setAddress(?string $address): static
    {
        if (is_null($address)) {
            throw new InvalidArgumentException('non-nullable address cannot be null');
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets traderName
     *
     * @return string|null
     */
    public function getTraderName(): ?string
    {
        return $this->container['traderName'];
    }

    /**
     * Sets traderName
     *
     * @param string|null $traderName traderName
     *
     * @return $this
     */
    public function setTraderName(?string $traderName): static
    {
        if (is_null($traderName)) {
            throw new InvalidArgumentException('non-nullable traderName cannot be null');
        }
        $this->container['traderName'] = $traderName;

        return $this;
    }

    /**
     * Gets traderStreet
     *
     * @return string|null
     */
    public function getTraderStreet(): ?string
    {
        return $this->container['traderStreet'];
    }

    /**
     * Sets traderStreet
     *
     * @param string|null $traderStreet traderStreet
     *
     * @return $this
     */
    public function setTraderStreet(?string $traderStreet): static
    {
        if (is_null($traderStreet)) {
            throw new InvalidArgumentException('non-nullable traderStreet cannot be null');
        }
        $this->container['traderStreet'] = $traderStreet;

        return $this;
    }

    /**
     * Gets traderPostalCode
     *
     * @return string|null
     */
    public function getTraderPostalCode(): ?string
    {
        return $this->container['traderPostalCode'];
    }

    /**
     * Sets traderPostalCode
     *
     * @param string|null $traderPostalCode traderPostalCode
     *
     * @return $this
     */
    public function setTraderPostalCode(?string $traderPostalCode): static
    {
        if (is_null($traderPostalCode)) {
            throw new InvalidArgumentException('non-nullable traderPostalCode cannot be null');
        }
        $this->container['traderPostalCode'] = $traderPostalCode;

        return $this;
    }

    /**
     * Gets traderCity
     *
     * @return string|null
     */
    public function getTraderCity(): ?string
    {
        return $this->container['traderCity'];
    }

    /**
     * Sets traderCity
     *
     * @param string|null $traderCity traderCity
     *
     * @return $this
     */
    public function setTraderCity(?string $traderCity): static
    {
        if (is_null($traderCity)) {
            throw new InvalidArgumentException('non-nullable traderCity cannot be null');
        }
        $this->container['traderCity'] = $traderCity;

        return $this;
    }

    /**
     * Gets traderCompanyType
     *
     * @return string|null
     */
    public function getTraderCompanyType(): ?string
    {
        return $this->container['traderCompanyType'];
    }

    /**
     * Sets traderCompanyType
     *
     * @param string|null $traderCompanyType traderCompanyType
     *
     * @return $this
     */
    public function setTraderCompanyType(?string $traderCompanyType): static
    {
        if (is_null($traderCompanyType)) {
            throw new InvalidArgumentException('non-nullable traderCompanyType cannot be null');
        }
        $this->container['traderCompanyType'] = $traderCompanyType;

        return $this;
    }

    /**
     * Gets traderNameMatch
     *
     * @return \Cone\Vies\Model\Match|null
     */
    public function getTraderNameMatch(): ?\Cone\Vies\Model\Match
    {
        return $this->container['traderNameMatch'];
    }

    /**
     * Sets traderNameMatch
     *
     * @param \Cone\Vies\Model\Match|null $traderNameMatch traderNameMatch
     *
     * @return $this
     */
    public function setTraderNameMatch(?\Cone\Vies\Model\Match $traderNameMatch): static
    {
        if (is_null($traderNameMatch)) {
            throw new InvalidArgumentException('non-nullable traderNameMatch cannot be null');
        }
        $this->container['traderNameMatch'] = $traderNameMatch;

        return $this;
    }

    /**
     * Gets traderStreetMatch
     *
     * @return \Cone\Vies\Model\Match|null
     */
    public function getTraderStreetMatch(): ?\Cone\Vies\Model\Match
    {
        return $this->container['traderStreetMatch'];
    }

    /**
     * Sets traderStreetMatch
     *
     * @param \Cone\Vies\Model\Match|null $traderStreetMatch traderStreetMatch
     *
     * @return $this
     */
    public function setTraderStreetMatch(?\Cone\Vies\Model\Match $traderStreetMatch): static
    {
        if (is_null($traderStreetMatch)) {
            throw new InvalidArgumentException('non-nullable traderStreetMatch cannot be null');
        }
        $this->container['traderStreetMatch'] = $traderStreetMatch;

        return $this;
    }

    /**
     * Gets traderPostalCodeMatch
     *
     * @return \Cone\Vies\Model\Match|null
     */
    public function getTraderPostalCodeMatch(): ?\Cone\Vies\Model\Match
    {
        return $this->container['traderPostalCodeMatch'];
    }

    /**
     * Sets traderPostalCodeMatch
     *
     * @param \Cone\Vies\Model\Match|null $traderPostalCodeMatch traderPostalCodeMatch
     *
     * @return $this
     */
    public function setTraderPostalCodeMatch(?\Cone\Vies\Model\Match $traderPostalCodeMatch): static
    {
        if (is_null($traderPostalCodeMatch)) {
            throw new InvalidArgumentException('non-nullable traderPostalCodeMatch cannot be null');
        }
        $this->container['traderPostalCodeMatch'] = $traderPostalCodeMatch;

        return $this;
    }

    /**
     * Gets traderCityMatch
     *
     * @return \Cone\Vies\Model\Match|null
     */
    public function getTraderCityMatch(): ?\Cone\Vies\Model\Match
    {
        return $this->container['traderCityMatch'];
    }

    /**
     * Sets traderCityMatch
     *
     * @param \Cone\Vies\Model\Match|null $traderCityMatch traderCityMatch
     *
     * @return $this
     */
    public function setTraderCityMatch(?\Cone\Vies\Model\Match $traderCityMatch): static
    {
        if (is_null($traderCityMatch)) {
            throw new InvalidArgumentException('non-nullable traderCityMatch cannot be null');
        }
        $this->container['traderCityMatch'] = $traderCityMatch;

        return $this;
    }

    /**
     * Gets traderCompanyTypeMatch
     *
     * @return \Cone\Vies\Model\Match|null
     */
    public function getTraderCompanyTypeMatch(): ?\Cone\Vies\Model\Match
    {
        return $this->container['traderCompanyTypeMatch'];
    }

    /**
     * Sets traderCompanyTypeMatch
     *
     * @param \Cone\Vies\Model\Match|null $traderCompanyTypeMatch traderCompanyTypeMatch
     *
     * @return $this
     */
    public function setTraderCompanyTypeMatch(?\Cone\Vies\Model\Match $traderCompanyTypeMatch): static
    {
        if (is_null($traderCompanyTypeMatch)) {
            throw new InvalidArgumentException('non-nullable traderCompanyTypeMatch cannot be null');
        }
        $this->container['traderCompanyTypeMatch'] = $traderCompanyTypeMatch;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
