<?php

declare(strict_types=1);
/**
 * CheckVatRequest
 *
 * PHP version 8.1
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vies on-the-Web Endpoint
 *
 * This is the contract for Vies on-the-Web endpoints. The checkVat service supports exact and approximate matching at the same time. In order to retrieve the requestIdentifier, the information about requesterMemberStateCode and requesterNumber have to be provided.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cone\Vies\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Cone\Vies\ObjectSerializer;

/**
 * CheckVatRequest Class Doc Comment
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CheckVatRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'CheckVatRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'countryCode' => 'string',
        'vatNumber' => 'string',
        'requesterMemberStateCode' => 'string',
        'requesterNumber' => 'string',
        'traderName' => 'string',
        'traderStreet' => 'string',
        'traderPostalCode' => 'string',
        'traderCity' => 'string',
        'traderCompanyType' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'countryCode' => null,
        'vatNumber' => null,
        'requesterMemberStateCode' => null,
        'requesterNumber' => null,
        'traderName' => null,
        'traderStreet' => null,
        'traderPostalCode' => null,
        'traderCity' => null,
        'traderCompanyType' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'countryCode' => false,
        'vatNumber' => false,
        'requesterMemberStateCode' => false,
        'requesterNumber' => false,
        'traderName' => false,
        'traderStreet' => false,
        'traderPostalCode' => false,
        'traderCity' => false,
        'traderCompanyType' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'countryCode' => 'countryCode',
        'vatNumber' => 'vatNumber',
        'requesterMemberStateCode' => 'requesterMemberStateCode',
        'requesterNumber' => 'requesterNumber',
        'traderName' => 'traderName',
        'traderStreet' => 'traderStreet',
        'traderPostalCode' => 'traderPostalCode',
        'traderCity' => 'traderCity',
        'traderCompanyType' => 'traderCompanyType',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'countryCode' => 'setCountryCode',
        'vatNumber' => 'setVatNumber',
        'requesterMemberStateCode' => 'setRequesterMemberStateCode',
        'requesterNumber' => 'setRequesterNumber',
        'traderName' => 'setTraderName',
        'traderStreet' => 'setTraderStreet',
        'traderPostalCode' => 'setTraderPostalCode',
        'traderCity' => 'setTraderCity',
        'traderCompanyType' => 'setTraderCompanyType',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'countryCode' => 'getCountryCode',
        'vatNumber' => 'getVatNumber',
        'requesterMemberStateCode' => 'getRequesterMemberStateCode',
        'requesterNumber' => 'getRequesterNumber',
        'traderName' => 'getTraderName',
        'traderStreet' => 'getTraderStreet',
        'traderPostalCode' => 'getTraderPostalCode',
        'traderCity' => 'getTraderCity',
        'traderCompanyType' => 'getTraderCompanyType',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('countryCode', $data ?? [], null);
        $this->setIfExists('vatNumber', $data ?? [], null);
        $this->setIfExists('requesterMemberStateCode', $data ?? [], null);
        $this->setIfExists('requesterNumber', $data ?? [], null);
        $this->setIfExists('traderName', $data ?? [], null);
        $this->setIfExists('traderStreet', $data ?? [], null);
        $this->setIfExists('traderPostalCode', $data ?? [], null);
        $this->setIfExists('traderCity', $data ?? [], null);
        $this->setIfExists('traderCompanyType', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets countryCode
     *
     * @return string|null
     */
    public function getCountryCode(): ?string
    {
        return $this->container['countryCode'];
    }

    /**
     * Sets countryCode
     *
     * @param string|null $countryCode countryCode
     *
     * @return $this
     */
    public function setCountryCode(?string $countryCode): static
    {
        if (is_null($countryCode)) {
            throw new InvalidArgumentException('non-nullable countryCode cannot be null');
        }
        $this->container['countryCode'] = $countryCode;

        return $this;
    }

    /**
     * Gets vatNumber
     *
     * @return string|null
     */
    public function getVatNumber(): ?string
    {
        return $this->container['vatNumber'];
    }

    /**
     * Sets vatNumber
     *
     * @param string|null $vatNumber vatNumber
     *
     * @return $this
     */
    public function setVatNumber(?string $vatNumber): static
    {
        if (is_null($vatNumber)) {
            throw new InvalidArgumentException('non-nullable vatNumber cannot be null');
        }
        $this->container['vatNumber'] = $vatNumber;

        return $this;
    }

    /**
     * Gets requesterMemberStateCode
     *
     * @return string|null
     */
    public function getRequesterMemberStateCode(): ?string
    {
        return $this->container['requesterMemberStateCode'];
    }

    /**
     * Sets requesterMemberStateCode
     *
     * @param string|null $requesterMemberStateCode requesterMemberStateCode
     *
     * @return $this
     */
    public function setRequesterMemberStateCode(?string $requesterMemberStateCode): static
    {
        if (is_null($requesterMemberStateCode)) {
            throw new InvalidArgumentException('non-nullable requesterMemberStateCode cannot be null');
        }
        $this->container['requesterMemberStateCode'] = $requesterMemberStateCode;

        return $this;
    }

    /**
     * Gets requesterNumber
     *
     * @return string|null
     */
    public function getRequesterNumber(): ?string
    {
        return $this->container['requesterNumber'];
    }

    /**
     * Sets requesterNumber
     *
     * @param string|null $requesterNumber requesterNumber
     *
     * @return $this
     */
    public function setRequesterNumber(?string $requesterNumber): static
    {
        if (is_null($requesterNumber)) {
            throw new InvalidArgumentException('non-nullable requesterNumber cannot be null');
        }
        $this->container['requesterNumber'] = $requesterNumber;

        return $this;
    }

    /**
     * Gets traderName
     *
     * @return string|null
     */
    public function getTraderName(): ?string
    {
        return $this->container['traderName'];
    }

    /**
     * Sets traderName
     *
     * @param string|null $traderName traderName
     *
     * @return $this
     */
    public function setTraderName(?string $traderName): static
    {
        if (is_null($traderName)) {
            throw new InvalidArgumentException('non-nullable traderName cannot be null');
        }
        $this->container['traderName'] = $traderName;

        return $this;
    }

    /**
     * Gets traderStreet
     *
     * @return string|null
     */
    public function getTraderStreet(): ?string
    {
        return $this->container['traderStreet'];
    }

    /**
     * Sets traderStreet
     *
     * @param string|null $traderStreet traderStreet
     *
     * @return $this
     */
    public function setTraderStreet(?string $traderStreet): static
    {
        if (is_null($traderStreet)) {
            throw new InvalidArgumentException('non-nullable traderStreet cannot be null');
        }
        $this->container['traderStreet'] = $traderStreet;

        return $this;
    }

    /**
     * Gets traderPostalCode
     *
     * @return string|null
     */
    public function getTraderPostalCode(): ?string
    {
        return $this->container['traderPostalCode'];
    }

    /**
     * Sets traderPostalCode
     *
     * @param string|null $traderPostalCode traderPostalCode
     *
     * @return $this
     */
    public function setTraderPostalCode(?string $traderPostalCode): static
    {
        if (is_null($traderPostalCode)) {
            throw new InvalidArgumentException('non-nullable traderPostalCode cannot be null');
        }
        $this->container['traderPostalCode'] = $traderPostalCode;

        return $this;
    }

    /**
     * Gets traderCity
     *
     * @return string|null
     */
    public function getTraderCity(): ?string
    {
        return $this->container['traderCity'];
    }

    /**
     * Sets traderCity
     *
     * @param string|null $traderCity traderCity
     *
     * @return $this
     */
    public function setTraderCity(?string $traderCity): static
    {
        if (is_null($traderCity)) {
            throw new InvalidArgumentException('non-nullable traderCity cannot be null');
        }
        $this->container['traderCity'] = $traderCity;

        return $this;
    }

    /**
     * Gets traderCompanyType
     *
     * @return string|null
     */
    public function getTraderCompanyType(): ?string
    {
        return $this->container['traderCompanyType'];
    }

    /**
     * Sets traderCompanyType
     *
     * @param string|null $traderCompanyType traderCompanyType
     *
     * @return $this
     */
    public function setTraderCompanyType(?string $traderCompanyType): static
    {
        if (is_null($traderCompanyType)) {
            throw new InvalidArgumentException('non-nullable traderCompanyType cannot be null');
        }
        $this->container['traderCompanyType'] = $traderCompanyType;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
