<?php
/**
 * Match
 *
 * PHP version 8.1
 *
 * @package  Cone\Vies
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vies on-the-Web Endpoint
 *
 * This is the contract for Vies on-the-Web endpoints. The checkVat service supports exact and approximate matching at the same time. In order to retrieve the requestIdentifier, the information about requesterMemberStateCode and requesterNumber have to be provided.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cone\Vies\Model;

/**
 * Match Class Doc Comment
 *
 * @package  Cone\Vies
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum Match: string
{
    case VALID = 'VALID';

    case INVALID = 'INVALID';

    case NOT_PROCESSED = 'NOT_PROCESSED';
}


